server:
  port: 8091

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: ProductService
  zipkin:
  base-url: http://localhost:9411/

sleuth:
  sampler:
    probability: 1 #100% (default = 10%)

    

  
  